FIND_PATH(LIBUI_INCLUDE_DIR NAMES ui.h)
FIND_LIBRARY(LIBUI_LIBRARY NAMES libui.so)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(libui
                                  DEFAULT_MSG
                                  LIBUI_LIBRARY
                                  LIBUI_INCLUDE_DIR)

MARK_AS_ADVANCED(LIBUI_INCLUDE_DIR LIBUI_LIBRARY)

SET(LIBUI_INCLUDE_DIRS "${LIBUI_INCLUDE_DIR}")
SET(LIBUI_LIBRARIES "${LIBUI_LIBRARY}")
